export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAILURE = 'login_failure'
export const LOGOUT_SUCCESS = 'logout_success'
export const LOGIN_USER = 'login_user'
export const REGISTER_USER = 'register_user'
export const GET_USER = 'auth_user'
export const LOGOUT_USER = 'logout_user'
